name: My Workflow

on: [pull_request]

jobs:
  runMultipleCommands:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v1
     - run: |
        apt install ffmpeg -y
        pip install -r requirements.txt
        python test.py
