name: My Workflow

on: [pull_request]

jobs:
  runMultipleCommands:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2.3.4
        with:
          lfs: 'true'
          submodules: 'recursive'
     - run: |
        sudo apt install ffmpeg -y
        pip install -r requirements.txt
        python test.py
