name: My Workflow

on: [pull_request]

jobs:
  runMultipleCommands:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v1
     - run: |
        curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
        sudo apt install ffmpeg git-lfs -y
        pip install -r requirements.txt
        python test.py
